sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
- '13'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: B1QYVItEPFrVM29ADSi/rrwGTfBzDEg4ULdcTolN2vUwZhQpyQs0tWfBpe0q5Oyrd0PN1qAzC02HlSUqUqMK9wguTXODGIgX0sukCQx/pAzPdydgtfroJphpJvemFuaRTY687kOXoXoWmNSw/VYWtaOHGC7B3yWcFK43/g9eFiM=
